name: Docker Image CI

on:
  push:
    branches: [ "github_action" ]   # testing
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --build-arg SIGNAL_BRANCH=v7.29.0 --output out .
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: Signal-7.29.0.AppImage
        path: ./out/Signal-7.29.0.AppImage
        retention-days: 5
